language: java

addons:
  ssh_known_hosts:
  - ftp.interlis.ch
  apt:
    packages:
    - python3
    - python3-pip

branches:
  only:
    - master
    - stable

install: true

before_script:
    - python3 --version
    - virtualenv -p python3 my_py3
    - source my_py3/bin/activate # to activate the python3 environemt    
    - python -m pip install docutils # use my_py3
    - python -m pip freeze

script: 
  - ./gradlew -Drst2html=`which rst2html.py` build usrdoc
deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew -Drepos_pwd=${repos_pwd} -Drepos_usr=jql_jars-INTE uploadArchives
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./gradlew -Drst2html=`which rst2html.py` -Dgithub_token=${github_token} -Drepos_pwd=${repos_pwd} -Drepos_usr=jql_jars-INTE '-Drelease=' -Ddownloads_pwd=${downloads_pwd} -Ddownloads_usr=jql_downloads uploadArchives uploadBin
    on:
      branch: stable
